# vim: noai ts=2:sw=2
baseURL = 'https://wallabra.github.io/'
languageCode = 'pt-br'
title = 'Gustavo Ramos Rehermann'
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  #homeSubtitle = "Portfólio & Blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Website pessoal de Gustavo Rehermann com portfólio, blog, e sobre"
  keywords = "homepage, portfolio, blog, person"
  images = [""]

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:rehermann6046@gmail.com"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/wallabra6046"

  [[params.social]]
    name = "instagram"
    url  = "https://instagram.com/wallabra6046/"

  [[params.social]]
    name = "facebook"
    url  = "http://facebook.com/gustavorehermann/"

  [[params.social]]
    name = "mastodon"
    url  = "https://bark.lgbt/@wallabra"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/gustavo-rehermann-4215bb65/"

  [[params.social]]
    name = "reddit"
    url  = "https://www.reddit.com/user/wallabra"

  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/@wallabra"

  [[params.social]]
    name = "twitch"
    url  = "https://twitch.tv/wallabra"

  [[params.social]]
    name = "github"
    url  = "https://github.com/wallabra"

  [[params.social]]
    name = "gitea"
    url  = "https://gitea.com/wallabra"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/wallabra"

  [[params.sociala]]
    name = "gpg"
    url  = "https://keys.openpgp.org/vks/v1/by-fingerprint/D8A4D1FCDFAD8C7408D95C73BC54C1B15C17148E"

  [[params.social]]
    name = "kofi"
    url  = "https://ko-fi.com/wallabra"

  [[params.social]]
    name = "matrix"
    url  = "https://matrix.to/#/@wallabra:bark.lgbt"

  [[params.social]]
    name = "discord"
    url  = "https://discord.com/users/208613174394486784"

  [[params.social]]
    name = "lichess"
    url  = "https://lichess.org/@/Gustavo6046"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en.params]
    title = "Gustavo Rehermann"
    homeSubtitle = "Software Developer, Graphics Designer, Digital Composer"
    keywords = "portfolio, blog, developer, designer, composer"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    # Highlight cards
    [languages.en.params.highlights]
      sectionTitle = "Portfolio Highlights"

    [[languages.en.params.highlights.items]]
      type          = "Software"
      name          = "neurs"
      description   = "Minimalistic artificial neural network Rust library"
      url           = "https://github.com/wallabra/neurs_project"

    [[languages.en.params.highlights.items]]
      type          = "Software"
      name          = "ZetaBot"
      description   = "AI that plays Doom and navigates a level"
      url           = "https://github.com/zeta-group/ZetaBot"
      image         = "https://github.com/zeta-group/ZetaBot/raw/master/ZetaBot-icon.svg"

    [[languages.en.params.highlights.items]]
      type          = "Music"
      name          = "Seismic"
      description   = "Music track assortment release from 2023"
      url           = "https://audiomack.com/wallabra/album/seismic"
      image         = "https://assets.audiomack.com/wallabra/b313338f84f04b3f4ef83611b2d6cef83689abc7dd1581fafc0a52a5156756c8.jpeg?type=album&max=true"

    [[languages.en.params.highlights.items]]
      type          = "Music"
      name          = "Made in Steel"
      description   = "Music track assortment release from 2022"
      url           = "https://audiomack.com/wallabra/album/made-in-steel"
      image         = "https://assets.audiomack.com/gustavo6046/d9bb5d3a4a7da0a699b6acf993754097f8490fbdc03fd83026cfa77e194febb5.jpeg?type=album&max=true"

    # Logo
    [languages.en.params.logo]
      logoText = "wallabra"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [languages.pt-br.params]
    title = "Gustavo Rehermann"
    homeSubtitle = "Desenvolvedor de Software, Designer Gráfico, Compositor Digital"
    keywords = "portfolio, blog, developer, designer, composer"
    readOtherPosts = "Ler mais posts"

    # Highlight cards
    [languages.pt-br.params.highlights]
      sectionTitle = "Destaques do Portfólio"

    [[languages.pt-br.params.highlights.items]]
      type        = "Software"
      name        = "neurs"
      description = "Biblioteca minimalista de redes neurais artificiais em Rust"
      url         = "https://github.com/wallabra/neurs_project"

    [[languages.pt-br.params.highlights.items]]
      type        = "Software"
      name        = "ZetaBot"
      description = "Bot inteligente que joga Doom e navega níveis"
      url         = "https://github.com/zeta-group/ZetaBot"
      image       = "https://github.com/zeta-group/ZetaBot/raw/master/ZetaBot-icon.svg"

    [[languages.pt-br.params.highlights.items]]
      type          = "Música"
      name          = "Seismic"
      description   = "Lançamento de 2023, de faixas de música sortidas"
      url           = "https://audiomack.com/wallabra/album/seismic"
      image         = "https://assets.audiomack.com/wallabra/b313338f84f04b3f4ef83611b2d6cef83689abc7dd1581fafc0a52a5156756c8.jpeg?type=album&max=true"


    [[languages.pt-br.params.highlights.items]]
      type          = "Música"
      name          = "Made in Steel"
      description   = "Lançamento de 2022, de faixas de música sortidas"
      url           = "https://audiomack.com/wallabra/album/made-in-steel"
      image         = "https://assets.audiomack.com/gustavo6046/d9bb5d3a4a7da0a699b6acf993754097f8490fbdc03fd83026cfa77e194febb5.jpeg?type=album&max=true"

    # Logojjjjjjjjjj
    [languages.pt-br.params.logo]
      logoText = "wallabra"
      logoHomeLink = "/"


  # And you can even create generic menu
  [[menu.main]]
    identifier = "livrezine"
    name       = "LivreZine"
    url        = "/livrezine"
  [[menu.main]]
    identifier = "lnr"
    name       = "Loot & Roam"
    url        = "/proto-lnr"
  [[menu.main]]
    identifier = "portfolio"
    name       = "Portfolios"
    url        = "/portfolio"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/aboutme/aboutme/"

[security.exec]
allow = ['asciidoctor']
